# Intonate SSML Tagging Rules
#
# Each rule contains:
# - name: a unique identifier
# - match: a regex pattern to find in basic Markdown (e.g., '##', '*')
# - tag: the SSML or text to insert using regex backreferences
# - description: a brief explanation of what the rule does
# - profile: either 'core' or 'extended'
#
# Profile types:
# - core: safe, basic SSML (e.g., <break>, <emphasis>) — default level
# - extended: richer or experimental SSML (e.g., <prosody>, <voice>)

rules:
  - name: heading_level_1
    match: "^# (.+)"
    tag: '<break time="500ms"/>\1'
    description: "Add a longer 500ms pause before H1 (Title) headings"
    profile: core

  - name: heading_level_2
    match: "^## (.+)"
    tag: '<break time="300ms"/>\1'
    description: "Add a quicker 300ms pause before H2 (subheading - large)"
    profile: core

  - name: heading_level_3
    match: "^### (.+)"
    tag: '<break time="200ms"/>\1'
    description: "Add a quick 200ms pause before H3 (subheading - smaller)"
    profile: core

  - name: heading_level_4
    match: "^#### (.+)"
    tag: '<break time="150ms"/>\1'
    description: "Pause before H4 heading"
    profile: core

  - name: heading_level_5
    match: "^##### (.+)"
    tag: '<break time="100ms"/>\1'
    description: "Pause before H5 heading"
    profile: core

  - name: heading_level_6
    match: "^###### (.+)"
    tag: '<break time="100ms"/>\1'
    description: "Pause before H6 heading"
    profile: core

  - name: blockquote
    match: "^> ?(.+)"
    tag: '<prosody pitch="low" rate="slow">\1</prosody>'
    description: "Use lower pitch and slower rate for blockquote text"
    profile: extended

  - name: ordered_list
    match: '^\s*\d+\. (.+)'
    tag: '<break time="200ms"/>\1'
    description: "Add a short pause before ordered list items"
    profile: core

  - name: unordered_list
    match: '^\s*- (.+)'
    tag: '<break time="200ms"/>\1'
    description: "Add a short pause before unordered list items"
    profile: core

  - name: bold_and_italic_text
    match: '\*\*\*(.+?)\*\*\*'
    tag: '<emphasis level="strong">\1</emphasis>'
    description: "Emphasise bold and italic text"
    profile: core

  - name: bold_text
    match: '\*\*(.+?)\*\*'
    tag: '<emphasis level="strong">\1</emphasis>'
    description: "Emphasise bold text"
    profile: core

  - name: italicized_text
    match: '(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)'
    tag: '<prosody volume="x-soft">\1</prosody>'
    description: "Whisper or soften italicized text"
    profile: extended

  - name: horizontal_rule
    match: "^---$"
    tag: '<break time="800ms"/>'
    description: "Long break for horizontal rule"
    profile: core

  - name: markdown_link_skip_url
    match: '\[([^\]]+)\]\(([^)]+)\)'
    tag: '\1'
    description: "Read only the link text, not the URL"
    profile: core
